// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClnLGla1PGCvJDxLRcdXaZH17__vwKDWM',
    appId: '1:1068117026550:web:e189fd4b88f461ac94aed7',
    messagingSenderId: '1068117026550',
    projectId: 'ourspace-6e53c',
    authDomain: 'ourspace-6e53c.firebaseapp.com',
    storageBucket: 'ourspace-6e53c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk1IjxTNdleqNdoZbbcQkYjGKihK-xE0Q',
    appId: '1:1068117026550:android:face5b6e980da33094aed7',
    messagingSenderId: '1068117026550',
    projectId: 'ourspace-6e53c',
    storageBucket: 'ourspace-6e53c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZtxWopVpPmsc9A-PEKPLQnHjqXzOJRbA',
    appId: '1:1068117026550:ios:537e2ac1f8184d0f94aed7',
    messagingSenderId: '1068117026550',
    projectId: 'ourspace-6e53c',
    storageBucket: 'ourspace-6e53c.firebasestorage.app',
    iosBundleId: 'com.example.ourspaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZtxWopVpPmsc9A-PEKPLQnHjqXzOJRbA',
    appId: '1:1068117026550:ios:537e2ac1f8184d0f94aed7',
    messagingSenderId: '1068117026550',
    projectId: 'ourspace-6e53c',
    storageBucket: 'ourspace-6e53c.firebasestorage.app',
    iosBundleId: 'com.example.ourspaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClnLGla1PGCvJDxLRcdXaZH17__vwKDWM',
    appId: '1:1068117026550:web:fa9fe0d6688e038b94aed7',
    messagingSenderId: '1068117026550',
    projectId: 'ourspace-6e53c',
    authDomain: 'ourspace-6e53c.firebaseapp.com',
    storageBucket: 'ourspace-6e53c.firebasestorage.app',
  );
}
